[tool.poetry]
name = "bookops-nypl-platform"
version = "0.5.0"
description = "BookOps Python wrapper around NYPL Platform API"
license = "MIT"
authors = ["Tomasz Kalata <klingaroo@gmail.com>", "Charlotte Kostelic <charlottekostelic@gmail.com>"]
exclude = ["bookops_nypl_platform/temp.py", "bookops_nypl_platform/temp/*"]
readme = "README.md"

keywords = ["api", "cataloging", "bibliographic records", "library metadata", "nypl"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32.3"

[tool.poetry.dev-dependencies]
pytest = "^8.3.3"
pytest-mock = "^3.14.0"
pytest-cov = "^5.0.0"
black = "^24.8.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = ["webtest: mark a test hitting live endpoints"]

[tool.coverage.run]
relative_files = true
source = ["."]

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312', 'py313']
include = '\.pyi?$'
exclude = '''
(
    /(
        \.eggs
       | \.git
       | \.hg
       | \.mypy_cache
       | \.tox
       | \.venv
       | _build
       | buck-out
       | build
       | dist
    )/
    | temp.py
)
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
