name: bookops-nypl-platform unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-versions: ["3.7", "3.8", "3.9", "3.10"]

   steps:
    - name: test
      run: |
        set
        NP_AGENT=${{ NP_AGENT}}
        set
      # - uses: actions/checkout@v2
      # - name: Set up Python ${{ matrix.python-version}}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version}}
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install -r requirements.txt
      #     python -m pip install -r dev-requirements.txt

      # - name: Test with pytest
      #   run: pytest --cov=bookops-nypl-platform/

      # - name: Send report to Coveralls
      #   uses: AndreMiras/coveralls-python-action@develop
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN}}
